config/routes.rb
Rails.application.routes.draw do
  resources :income_items

  resources :income_categories

  resources :items

  resources :categories

  root "items#new"
end

app/models/item.rb
class Item < ActiveRecord::Base

  belongs_to :category

  validates_presence_of :category
  validates :money, numericality: true, presence: true

  attr_accessor :detail

  class << self
    def of_day(date = Date.current)
      date = Date.current if date.blank?
      where('date = ?', date.to_date)
    end

    def of_month(time = Time.now)
      time = Time.now if time.blank?
      where('date BETWEEN ? AND ?', time.beginning_of_month, time.end_of_month)
    end

    def of_year(time = Time.now)
      time = Time.now if time.blank?
      where('date BETWEEN ? AND ?', time.beginning_of_year, time.end_of_year)
    end
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  # GET /items
  # GET /items.json
  def index
    # @items = Item.all
    now = Time.now
    @year_total = Item.of_year.sum(:money)
    @month_total = Item.of_month.sum(:money)
    @day_total = Item.of_day.sum(:money)
    @today_items = Item.of_day

    @recent_10_days_total = Item.where("created_at > current_timestamp - INTERVAL '9' DAY")
        .select("DATE(date) AS day, SUM(items.money) AS total, items.date")
        .group('day, date')
        .order('date asc')

    @recent_10_months_total = Item.where("created_at > current_timestamp - INTERVAL '9' MONTH")
        .select("EXTRACT(MONTH FROM date) AS month, SUM(items.money) AS total")
        .group('month')
        .order('month asc')
    @items = Item.all
  end

  # GET /items/1
  # GET /items/1.json
  def show
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to items_path }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:category_id, :description, :date, :money)
    end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.erb
<%= form_for(@item) do |f| %>
  <% if @item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% @item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class='translation'>
    选择分类：<span class='cate'><%= @item.category.try(:name) %></span><br>
    花费：<span class='money'><%= @item.money %></span>元
  </div>
  
  <%= f.hidden_field :category_id %>
  <%= f.hidden_field :money %>

  <div class="field">
    <%= f.label :detail %><br>
    <%= f.text_field :detail %>
  </div>

  <div class="field">
    <%= f.label :date %><br>
    <%= f.date_select :date %>
  </div>
  <div class="actions">
    <%= f.submit "提交" %>
  </div>
<% end %>

<script type="text/javascript">
  var categories, cateCode, cateId, money, map = {};

  $(function (event) {
    $('#item_detail').keyup(function (event) {
      var $input = $(this)
        , value = $input.val().replace('，', ',') // replace chinese comma to english comma
        , newCateCode;

      // comma is the key
      if (!~value.indexOf(',')) {
        if (end_with_number(value)) {
          var index = 1 * value[value.length - 1]
            , category = categories[index - 1];

          cateId = category.id;
          $('#item_category_id').val(cateId);

          refresh_translation_category([category])
        } else if (value !== '' && value !== null) {
          $.getJSON('/categories?pinyin=' + value)
           .then(translate);
        }
      } else {
        money = value.split(',')[1];
        $('#item_money').val(money);

        refresh_translation_money(money);
      }

      function translate (data, status) {
        if (data.length == 1) {
          cateId = data[0]['id'];
          $('#item_category_id').val(cateId);

          refresh_translation_category(data);
        } else {
          categories = data;
          if (categories.length > 9) {
            categories.length = 9;
          }

          refresh_translation_category(data);
        }
      }

      function get_number_photo (number) {
        var photo_map = {
          1: '①',
          2: '②',
          3: '③',
          4: '④',
          5: '⑤',
          6: '⑥',
          7: '⑦',
          8: '⑧',
          9: '⑨'
        }
        return photo_map[number + 1];
      }

      function refresh_translation_category (data) {
        var $cate = $('.translation .cate');

        if (data.length === 0) {
          $cate.html("No Category Selected!");
        } else if (data.length === 1) {
          $cate.html(data[0]["name"]);
        } else {
          var html = $.map(data, function (item, index, en) {
            return get_number_photo(index) + item.name;
          }).join(', ');
          $cate.html(html);
        }
      }

      function refresh_translation_money (money) {
        $('.translation .money').html(money);
      }

      function end_with_number(value) {
        if (value.length === 0) return false;

        return (1 * value[value.length - 1]) > 0;
      }
    });
  });
</script>

app/views/items/edit.html.erb
<h1>Editing item</h1>

<%= render 'form' %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

app/views/items/index.html.erb
<h3>支出一览表</h3>

<!-- summary of year, month and today's expanding -->
<table class='table'>
  <thead>
    <tr>
      <th>时段</th>
      <th>支出</th>
      <th>收入</th>
    </tr>
  </thead>

  <tbody>
    <tr>
      <td>本年</td>
      <td><%= @year_total %></td>
      <td></td>
    </tr>
    <tr>
      <td>本月</td>
      <td><%= @month_total %></td>
      <td></td>
    </tr>
    <tr>
      <td>今天</td>
      <td><%= @day_total %></td>
      <td>/</td>
    </tr>
  </tbody>
</table>

<!-- list of today's items -->
<table class='table'>
  <thead>
    <tr>
      <th>序号</th>
      <th>分类</th>
      <th>金额</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @today_items.each_with_index do |item, index| %>
      <tr>
        <td><%= index + 1 %></td>
        <td><%= item.category.name %></td>
        <td><%= item.money %></td>
        <td><%= link_to "更改", edit_item_path(item) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<% @recent_10_days_total.each_slice(5) do |days_total| %>
  <table class='table'>
    <thead>
      <tr>
      <% days_total.each do |day_total| %>
        <th>
          <%= "#{day_total.date.month}月#{day_total.date.day}日" %>
        </th>
      <% end %>
      </tr>
    </thead>
    <tbody>
        <tr>
          <% days_total.each do |day_total| %>
            <td><%= day_total.total %></td>
          <% end %>        
        </tr>
    </tbody>
  </table>
<% end %>

<table class='table'>
  <thead>
    <tr>
    <% @recent_10_months_total.each do |day_total| %>
      <th>
        <%= "#{day_total.month.to_i}月" %>
      </th>
    <% end %>
    </tr>
  </thead>
  <tbody>
      <tr>
        <% @recent_10_months_total.each do |day_total| %>
          <td><%= day_total.total %></td>
        <% end %>        
      </tr>
  </tbody>
</table>

<%= link_to 'New Item', new_item_path %>

app/views/items/index.txt.erb
<% @items.each do |item| %>
  category: <%= item.category.name %>, description: '<%= item.description %>', date: '<%= item.date %>', created_at: '<%= item.created_at %>', updated_at: '<%= item.updated_at %>', money: <%= item.money %>
<% end %>

app/views/items/new.html.erb
<h4>创建一条消费记录</h4>

<%= render 'form' %>

<p>
<%= link_to '返回', items_path, class: 'btn btn-default' %>
<%= link_to "编辑分类", categories_path, class: 'btn btn-default' %>

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Category:</strong>
  <%= @item.category.name %>
</p>

<p>
  <strong>Money:</strong>
  <%= @item.money %>
</p>

<p>
  <strong>Date:</strong>
  <%= @item.date %>
</p>

<%= link_to 'Edit', edit_item_path(@item) %> |
<%= link_to 'Back', items_path %>