config/routes.rb
Rails.application.routes.draw do
  resources :income_items

  resources :income_categories

  resources :items

  resources :categories

  root "items#new"
end

app/models/income_category.rb
class IncomeCategory < ActiveRecord::Base
  before_save :generate_pinyin

  has_ancestry

  class << self
    def find_by_pinyin(name)
      return all if name.blank?

      pinyin = PinYin.of_string(name).join
      where("pinyin LIKE ?", "%#{pinyin}%")
    end
  end

  protected
    def generate_pinyin
      if new_record? || name_changed?
        self.pinyin = "#{PinYin.of_string(name).join}_#{PinYin.abbr(name)}"
      end
    end
end

app/controllers/income_categories_controller.rb
class IncomeCategoriesController < ApplicationController
  before_action :set_income_category, only: [:show, :edit, :update, :destroy]

  # GET /income_categories
  # GET /income_categories.json
  def index
    @income_categories = IncomeCategory.all
  end

  # GET /income_categories/1
  # GET /income_categories/1.json
  def show
  end

  # GET /income_categories/new
  def new
    @income_category = IncomeCategory.new
  end

  # GET /income_categories/1/edit
  def edit
  end

  # POST /income_categories
  # POST /income_categories.json
  def create
    @income_category = IncomeCategory.new(income_category_params)

    respond_to do |format|
      if @income_category.save
        format.html { redirect_to @income_category, notice: 'Income category was successfully created.' }
        format.json { render :show, status: :created, location: @income_category }
      else
        format.html { render :new }
        format.json { render json: @income_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /income_categories/1
  # PATCH/PUT /income_categories/1.json
  def update
    respond_to do |format|
      if @income_category.update(income_category_params)
        format.html { redirect_to @income_category, notice: 'Income category was successfully updated.' }
        format.json { render :show, status: :ok, location: @income_category }
      else
        format.html { render :edit }
        format.json { render json: @income_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /income_categories/1
  # DELETE /income_categories/1.json
  def destroy
    @income_category.destroy
    respond_to do |format|
      format.html { redirect_to income_categories_url, notice: 'Income category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_income_category
      @income_category = IncomeCategory.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def income_category_params
      params.require(:income_category).permit(:name, :ancestry, :pinyin)
    end
end

app/helpers/income_categories_helper.rb
module IncomeCategoriesHelper
end

app/views/income_categories/_form.html.erb
<%= form_for(@income_category) do |f| %>
  <% if @income_category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@income_category.errors.count, "error") %> prohibited this income_category from being saved:</h2>

      <ul>
      <% @income_category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :ancestry %><br>
    <%= f.text_field :ancestry %>
  </div>
  <div class="field">
    <%= f.label :pinyin %><br>
    <%= f.text_field :pinyin %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/income_categories/edit.html.erb
<h1>Editing income_category</h1>

<%= render 'form' %>

<%= link_to 'Show', @income_category %> |
<%= link_to 'Back', income_categories_path %>

app/views/income_categories/index.html.erb
<h1>Listing income_categories</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Ancestry</th>
      <th>Pinyin</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @income_categories.each do |income_category| %>
      <tr>
        <td><%= income_category.name %></td>
        <td><%= income_category.ancestry %></td>
        <td><%= income_category.pinyin %></td>
        <td><%= link_to 'Show', income_category %></td>
        <td><%= link_to 'Edit', edit_income_category_path(income_category) %></td>
        <td><%= link_to 'Destroy', income_category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Income category', new_income_category_path %>

app/views/income_categories/new.html.erb
<h1>New income_category</h1>

<%= render 'form' %>

<%= link_to 'Back', income_categories_path %>

app/views/income_categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @income_category.name %>
</p>

<p>
  <strong>Ancestry:</strong>
  <%= @income_category.ancestry %>
</p>

<p>
  <strong>Pinyin:</strong>
  <%= @income_category.pinyin %>
</p>

<%= link_to 'Edit', edit_income_category_path(@income_category) %> |
<%= link_to 'Back', income_categories_path %>