config/routes.rb
Rails.application.routes.draw do
  resources :income_items

  resources :income_categories

  resources :items

  resources :categories

  root "items#new"
end

app/models/income_item.rb
class IncomeItem < ActiveRecord::Base
  belongs_to :income_category
end

app/controllers/income_items_controller.rb
class IncomeItemsController < ApplicationController
  before_action :set_income_item, only: [:show, :edit, :update, :destroy]

  # GET /income_items
  # GET /income_items.json
  def index
    @income_items = IncomeItem.all
  end

  # GET /income_items/1
  # GET /income_items/1.json
  def show
  end

  # GET /income_items/new
  def new
    @income_item = IncomeItem.new
  end

  # GET /income_items/1/edit
  def edit
  end

  # POST /income_items
  # POST /income_items.json
  def create
    @income_item = IncomeItem.new(income_item_params)

    respond_to do |format|
      if @income_item.save
        format.html { redirect_to @income_item, notice: 'Income item was successfully created.' }
        format.json { render :show, status: :created, location: @income_item }
      else
        format.html { render :new }
        format.json { render json: @income_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /income_items/1
  # PATCH/PUT /income_items/1.json
  def update
    respond_to do |format|
      if @income_item.update(income_item_params)
        format.html { redirect_to @income_item, notice: 'Income item was successfully updated.' }
        format.json { render :show, status: :ok, location: @income_item }
      else
        format.html { render :edit }
        format.json { render json: @income_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /income_items/1
  # DELETE /income_items/1.json
  def destroy
    @income_item.destroy
    respond_to do |format|
      format.html { redirect_to income_items_url, notice: 'Income item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_income_item
      @income_item = IncomeItem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def income_item_params
      params.require(:income_item).permit(:income_category_id, :money, :date)
    end
end

app/helpers/income_items_helper.rb
module IncomeItemsHelper
end

app/views/income_items/_form.html.erb
<%= form_for(@income_item) do |f| %>
  <% if @income_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@income_item.errors.count, "error") %> prohibited this income_item from being saved:</h2>

      <ul>
      <% @income_item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :income_category_id %><br>
    <%= f.text_field :income_category_id %>
  </div>
  <div class="field">
    <%= f.label :money %><br>
    <%= f.text_field :money %>
  </div>
  <div class="field">
    <%= f.label :date %><br>
    <%= f.date_select :date %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/income_items/edit.html.erb
<h1>Editing income_item</h1>

<%= render 'form' %>

<%= link_to 'Show', @income_item %> |
<%= link_to 'Back', income_items_path %>

app/views/income_items/index.html.erb
<h1>Listing income_items</h1>

<table>
  <thead>
    <tr>
      <th>Income category</th>
      <th>Money</th>
      <th>Date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @income_items.each do |income_item| %>
      <tr>
        <td><%= income_item.income_category %></td>
        <td><%= income_item.money %></td>
        <td><%= income_item.date %></td>
        <td><%= link_to 'Show', income_item %></td>
        <td><%= link_to 'Edit', edit_income_item_path(income_item) %></td>
        <td><%= link_to 'Destroy', income_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Income item', new_income_item_path %>

app/views/income_items/new.html.erb
<h1>New income_item</h1>

<%= render 'form' %>

<%= link_to 'Back', income_items_path %>

app/views/income_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Income category:</strong>
  <%= @income_item.income_category %>
</p>

<p>
  <strong>Money:</strong>
  <%= @income_item.money %>
</p>

<p>
  <strong>Date:</strong>
  <%= @income_item.date %>
</p>

<%= link_to 'Edit', edit_income_item_path(@income_item) %> |
<%= link_to 'Back', income_items_path %>